# Generated by Django 5.2 on 2025-05-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_class_student_charged_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tech_stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
