# Generated by Django 5.2 on 2025-05-06 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher_tech_stripe_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='tech_stripe_account_id',
            new_name='stripe_account_id',
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.teacher'),
            preserve_default=False,
        ),
    ]
