# Generated by Django 5.2 on 2025-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_tech_stripe_account_id_teacher_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='price',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='class',
            name='stripe_account_id',
        ),
        migrations.AddField(
            model_name='student',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
